name: Ansible Actions
on: push

jobs:
  Ansible-Actions:
    runs-on: target2
    steps:
      - name: Test Ansible-version
        run: |
          ansible --version
          cat /etc/os-release
          whoami
  Ansible-Playbook:
    runs-on: target2
    steps:
      - name: Fisrt Ansible-Playbook
        run: |
          cd /ansible
          ansible-playbook -b --extra-vars 'target=target_jb1' playbooks/getFreeMemory.yml
  Ansible-Playbook-OS-PATCHING:
    runs-on: target2
    steps:
      - name: OS PATCHING Ansible-Playbook
        run: |
          cd /ansible
          ansible-playbook -b --extra-vars 'target=target_jb1' playbooks/getFreeMemory.yml
          # ansible-playbook -b --extra-vars 'target=target_jb1' playbooks/OS-Patching.yml
        

