name: matrix
on: push

jobs:
  node-version:
    strategy:
      matrix: 
       node-version: [6,8,10]
      max-parallel: 2
    runs-on: ubuntu-latest
    steps:
      - name: Log Node node-version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 6
      - name: Log node node-version
        run: node -v