name: shell Commands

on: [pull_request]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps: 
      - name: echo a string TESTING
        run: echo "Hello world"
      - name: multiline Scritt TESTING
        run: |
          node -v
          npm -v
      - name: Python Command TESTING
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-commands123:
    runs-on: windows-latest
    needs: [run-shell-command]
    steps:
      - name: Directory Powershell TESTING
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash