name: shell Commands

on: [push]

jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string TESTING
        run: echo "Hello world"
      - name: multiline Scritt TESTING
        run: |
          node -v
          npm -v
      - name: Python Command TESTING
        run: |
          import platform
          print
          (platform.processor())
        shell: python